name: Update Bid Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  # 강제 트리거용
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 저장소 불러오기
      uses: actions/checkout@v3

    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 크롤러 실행
      run: python crawler.py

    - name: 결과 커밋
      run: |
        git config --global user.name 'auto-crawler'
        git config --global user.email 'bot@example.com'
        git add bid-data.json
        git commit -m "자동 업데이트: 공고 데이터 최신화" || echo "변경사항 없음"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

